name: Android Debug APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble Debug APK
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp app/build/outputs/apk/debug/app-debug.apk "dist/SplitPaisa-${{ github.run_number }}-debug.apk"

      - name: Upload artifact (no compression)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: dist/SplitPaisa-${{ github.run_number }}-debug.apk
          compression-level: 0
          retention-days: 7

      - name: Publish APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: debug-${{ github.run_id }}
          name: "SplitPaisa Debug #${{ github.run_number }}"
          prerelease: true
          files: dist/SplitPaisa-${{ github.run_number }}-debug.apk
