name: Android Debug APK (bootstrap Gradle 8.11.1)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Detect project root (settings.gradle)
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          SETTINGS=$(git ls-files | grep -E '(^|/)(settings\.gradle(\.kts)?)$' | head -n 1 || true)
          if [ -z "${SETTINGS:-}" ]; then
            echo "Could not find settings.gradle(.kts) anywhere in the repo." >&2
            exit 1
          fi
          PROJECT_DIR="$(dirname "$SETTINGS")"
          echo "project_dir=$PROJECT_DIR" >> "$GITHUB_OUTPUT"
          echo "Detected project dir: $PROJECT_DIR"

      - name: Download Gradle 8.11.1
        id: gradle_dl
        shell: bash
        run: |
          set -euo pipefail
          GV="8.11.1"
          URL="https://services.gradle.org/distributions/gradle-${GV}-bin.zip"
          echo "Downloading $URL"
          curl -sSL "$URL" -o gradle.zip
          unzip -q gradle.zip -d "$RUNNER_TEMP/gradle"
          echo "gradle_home=$RUNNER_TEMP/gradle/gradle-$GV" >> "$GITHUB_OUTPUT"
          "$RUNNER_TEMP/gradle/gradle-$GV/bin/gradle" --version

      - name: Assemble Debug APK (no wrapper)
        working-directory: ${{ steps.detect.outputs.project_dir }}
        run: ${{ steps.gradle_dl.outputs.gradle_home }}/bin/gradle :app:assembleDebug --no-daemon --stacktrace

      - name: Prepare artifact
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist
          APK=$(find app/build/outputs/apk/debug -maxdepth 1 -type f -name "*.apk" | head -n 1 || true)
          if [ -z "${APK:-}" ]; then
            echo "Debug APK not found under app/build/outputs/apk/debug." >&2
            echo "Directory listing for app/build/outputs:"
            find app/build/outputs -maxdepth 3 -type f -printf "%p\n" || true
            exit 1
          fi
          cp "$APK" "dist/SplitPaisa-${{ github.run_number }}-debug.apk"
          echo "Copied $APK"

      - name: Upload artifact (no compression)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ steps.detect.outputs.project_dir }}/dist/SplitPaisa-${{ github.run_number }}-debug.apk
          compression-level: 0
          retention-days: 7
